const PRODUCTS = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FETCH_PRODUCTS_PENDING: "FETCH_PRODUCTS_PENDING",
  FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_FAILURE: "FETCH_PRODUCTS_FAILURE",

  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_ITEM: "REMOVE_ITEM",
  SUB_QUANTITY: "SUB_QUANTITY",
  ADD_QUANTITY: "ADD_QUANTITY",

  CHECKOUT_PRODUCTS: "CHECKOUT_PRODUCTS",
  CHECKOUT_PRODUCTS_PENDING: "CHECKOUT_PRODUCTS_PENDING",
  CHECKOUT_PRODUCTS_SUCCESS: "CHECKOUT_PRODUCTS_SUCCESS",
  CHECKOUT_PRODUCTS_FAILURE: "CHECKOUT_PRODUCTS_FAILURE",
};

export default PRODUCTS;
